spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/engtalkmo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true

  sql:
    init.mode: always

jwt:
  issuer: shajh2210@gmail.com
  secret_key: study-springboot